### ISSUE TITLE
Logbook Column Header Sorting Filters

### ISSUE THREAD

**Issue by GimbalDCS** [engines-wafu/dcs_server_logbook#5]
![image](https://github.com/engines-wafu/dcs_server_logbook/assets/119107932/17d6e1c5-6941-4169-a57c-c97c27bf0e0d)

If you could, that'd help speed up some admin.

Cheers

**Comment by engines-wafu** [comment]
@GimbalDCS, when I look at this, will it also be more appropriate for each set of squadron pilots to be sorted by type hours?  Right now it's done on total hours.

**Comment by GimbalDCS** [comment]
@engines-wafu yep that would make sense for each sqn for sure.

**Comment by engines-wafu** [comment]
Done: https://github.com/engines-wafu/dcs_server_logbook/commit/7961949117e83f68797a6a6f1a8af2af126b9cf0
