### ISSUE TITLE
Function Request - Ability to show a list of pilots who currently have a qualification assigned 

### ISSUE THREAD

**Issue by jmailman11** [engines-wafu/dcs_server_logbook#7]
Function Request - Ability to show a list of pilots who currently have a qualification assigned.

Would be very useful for quickly determining how many and which pilots have a qualification. Would greatly speed up maintaining a squadrons qualification status. 

Possible solution:

!show_qualification_status

Returns a list allowing selection of which qualification you would like to search for.

Selection of an option then shows a list of all pilots who currently have that qualification.

**Comment by engines-wafu** [comment]
Done: https://github.com/engines-wafu/dcs_server_logbook/commit/2c12e8210831bbcf350df5dfda8f83c36d03ed2c
